# Generated by Django 2.1.5 on 2019-01-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='cart_id',
            new_name='cartID',
        ),
    ]
